---
title: "R Notebook"
output: html_notebook
---

If there are a few missing data points in the dataset, use the KNN to fix them (if needed) or remove them. If you want to use other methods to fill in the missing data points, please explain what it is and why it works well with your dataset. If there are may missing points, please figure out whether those are meaningful missing points or truly missing points. Think about and suggest how to treat them. If you want to use a method, please explain why it might work well. (Discuss with your teammates.)

Examine the dataset by using scatter plot matrix (see page 83 Figure 3.6 in the textbook). If there are too many variables you can split it into multiple matrices to be legible.

Use histograms (quantitative variable) or bar plots (quantitative variable) to see the distribution of each variable in the dataset. Report your findings.

```{r}

# load libraries

library(ggplot2)
library(corrplot)
library(ggpubr)

getwd()
# import data set



# Data Cleaning

#remove the column with only one unique numbers
which(apply(data, 2, var)==0)
print(c("unique of this column:",unique(data$Net.Income.Flag)))
data<-subset(data,select=-Net.Income.Flag)
```
